### ISSUE TITLE
StackExchange Sites

### ISSUE THREAD

**Issue by reshinthadithyan** [CarperAI/Code-Pile#1]
## StackExchange

**Dataset URL** - The data dump can be used to obtain all the dumps [here](https://data.stackexchange.com/)

Does the dataset exist in a scraped format?   

## Description
Stack Exchange is a network of question-and-answer websites on topics in diverse fields, each site covering a specific topic, where questions, answers, and users are subject to a reputation award process. The reputation system allows the sites to be self-moderating.

## Potential sites
 The Entire Stack Exchange Dump.

## Procedure

- [ ]  Download all the dumps
- [ ]  Formulate appropriate filters if at all we want to.
- [ ]  Processing and formatting.
- [ ]  `lm_dataformat` Processing

**Comment by flowpoint** [comment]
Hi, i have started working on this

**Comment by ncoop57** [comment]
> Hi, i have started working on this

Awesome, please make sure to check the original Pile: https://github.com/EleutherAI/the-pile

To make sure we aren't doing duplicate work

**Comment by reshinthadithyan** [comment]
@flowpoint, Look at this https://github.com/EleutherAI/stackexchange-dataset

**Comment by flowpoint** [comment]
i know about the similar scripts by collin and sdtblck
we surely can merge and improve their functions, i try to write modular code anyway
i've gone ahead and written less scripty code in #6
have a look and feel free to merge/comment
it strongly sounded, like we're assigned to the stackexchange data and still have to watch out with coordination and consolidation to prevent further duplicated work

**Comment by dmahan93** [comment]
Additional stack exchanges that don't fall under technology that may be useful:

https://cs.stackexchange.com/
https://cstheory.stackexchange.com/
https://opensource.stackexchange.com/
https://cseducators.stackexchange.com/

**Comment by tmabraham** [comment]
@reshinthadithyan Just some details about StackExchange archives based on my experience with the Code Review project.

The StackExchange archives are saved as XML files which can be hard to work with so we converted them to JSON files with [this script](https://github.com/CarperAI/CodeReviewSE/blob/main/xml_to_json.py). 

The formatting of code is a little weird so I manually added `<code>` tags:
https://github.com/CarperAI/CodeReviewSE/blob/cd2af9c1df1e617c42f7865e21ec0746bffb2579/data/helper.py#L21

Creating an lm_dataformat file is pretty easy, it's just:
```
ar = Archive('dataset')
ar.add_data(text)
ar.commit(archive_name)
```

**Comment by tmabraham** [comment]
Other websites to potentially include:
* Super User
* Tex - LaTeX
* Unix & Linux
* Information Security
* Database Administrators
* Artificiall Intelligence
* Data Science
* Blender
* Emacs
* VI and Vim
* Internet of Things
* Quantum Computing 
* Computer Graphics
* DevOps

**Comment by ncoop57** [comment]
There is this scraping script that might be useful: https://gist.github.com/craffel/a1e2aff893776d0ef2b0a95ed0fd7e7a

**Comment by reshinthadithyan** [comment]
Looked at https://gist.github.com/craffel/a1e2aff893776d0ef2b0a95ed0fd7e7a. This script processes questions and answers into a stream of paras. Which is a good post-processing exercise for modeling. But I guess for us, retaining upvotes and other metadata makes a lot of sense for cataloging as an intermediate. I guess we can go ahead with adapting @tmabraham's CodeReviewSE(https://github.com/CarperAI/CodeReviewSE) scripts, Which retain the complete metadata. Later we can post-process per our need.

**Comment by reshinthadithyan** [comment]
The dump for each site has the following files, `Badges.xml, PostHistory.xml, Posts.xml, Users.xml, Comments.xml, PostLinks.xml, Tags.xml, Votes.xml`. We'll want to process the entire site dump into a file,
## Preprocessed Format:
`SitePost.json` - Wherein the entire site's posts are dumped here. `post_id` is the key and all the related `comments`, `answers`, and `user_infos` of users interacting in the post are under them.   
**Note :** This is a clean way to store all the metadata in a singular format.
## PostProcessed Format:
For the post-processed version, we'll want to convert the pre-processed dataset into [lm_dataformat](https://github.com/EleutherAI/lm_dataformat) with a conversation-like format ?

### Need for Preprocessed and Postprocessed format
The reason that we would want to maintain these two formats is that we're still unclear about how we're going to prompt.

@ncoop57, thoughts ?

**Comment by ncoop57** [comment]
Yeah, we can go ahead and store in this format while we finalize the final lm_dataformat

**Comment by flowpoint** [comment]
I've come up with this intermediate document structure oriented around a stackexchange site/document/thread.
It erases quite some fields.
Some because they look too granular/ unmatchable with other datasets (like votes).
Other ones, like Edit-history are nontrivial and can be considered later.
Dates are kept for distribution analysis.

[dump data schema for reference](https://meta.stackexchange.com/questions/2677/database-schema-documentation-for-the-public-data-dump-and-sede)

intermediate structure as pseudocode/python/pydantic:
```
class Comment(BaseModel):    
    user_id: str    
    score: int    
    creation_date: datetime    
    text: str    
     
     
class User(BaseModel):        
    user_id: str
    reputation: int                                
    upvotes: int                                   
    downvotes: int                                 
    profileviews: int                              
    creationdate: datetime                         
    # this is not pure text                        
    aboutme: str                                   
                                                   
                               
class Post(BaseModel):         
    # ids                      
    post_id: int                                   
    user_id: str                                   
                                                   
    # main post text                                                
    title: str                                                              
    text: str                  
    comments: list[Comment]    
                                
    score: int                  
    tags: list[str]             
    favourite_count: int                                                     
    view_count: int                                                          
    creation_date: datetime                                                  
    last_edit_date: datetime                                                 
                                                                             
                                                                             
# this should represent a single document/jsonl line                              
class StackExchangeDoc(BaseModel):                                           
    question: Post                                                           
    answers: list[Post]                                                      
    accepted_answer_post_id: int      
    users: list[Users]

```

**Comment by vanga** [comment]
I am working on denormalising the data. 
Below is a denormalized sample with just the relations mentioned by @flowpoint above. I haven't excluded any columns from any table. Eventually, we would only want some columns to be included in the final output.

https://gist.github.com/vanga/b1f1a4a6d82accd69ba35c0f33b76435

Excluded relations: Votes, Badges, PostHistory, PostLinks
If we need to include all the relations, we could do that.

**Comment by ncoop57** [comment]
@reshinthadithyan  and @vanga  please make sure to add this information to the issue description:

## Tests

Include a dummy_dataset.parquet file to test your code against. This dummy_dataset should include the columns for the data and metadata associated with the dataset, which will then be converted into the final format for language model consumption, along with an example row or rows that you can verify your code correctly collects. In addition to this file, include the unit test that evaluates your code against this dummy_dataset.

Give an example of the columns and data:

| col1 | col2 | .... |
| ---- | ---- | ---- |
| row1 | row1 | .... |

**Comment by reshinthadithyan** [comment]
@ncoop57, https://github.com/CarperAI/Code-Pile/issues/1#issuecomment-1257333026 This should be a separate issue so that people are aware of it. I'm adding the same in the Issue template.

**Comment by vanga** [comment]
For anyone working on this, current version of the dumps seem to be [corrupted](https://meta.stackexchange.com/questions/382654/issues-decompressing-the-october-2022-dump)
Old version can be found here https://archive.org/details/stackexchange_20220606
