### ISSUE TITLE
Programming and Computing Books

### ISSUE THREAD

**Issue by taisazero** [CarperAI/Code-Pile#12]
## Open Access and Free Programming and Computing Books

Dataset URL - [Computing Wikibooks](https://en.wikibooks.org/wiki/Department:Computing). We can download the dump [here](https://dumps.wikimedia.org/enwikibooks/20220901/) and filter for computing wikibooks. 
[Free Computing Books](https://github.com/EbookFoundation/free-programming-books) -- not sure if the books on here are safe to use we need to check.

Does the dataset exist in a scraped format?   Yes if HTML/website No if the book is in PDF.

## Description
Books contain rich information and present cumulations of knowledge on specific topics. It could also be home to exercises and solutions. If a model is pretrained on it could perhaps enhance its chain of thought capabilities.

## Procedure
* [x] Process WikiBooks dataset
* [ ] Scrape PDF books into text
* [ ] Scrape books in websites/webpages
* [ ] Deduplicate and store in s3
* [ ] Run lm_format.

**Comment by taisazero** [comment]
Who wants to work on this with me? We need help from scarpers

**Comment by PhungVanDuy** [comment]
@taisazero  let me work on this one. Can you update your current status?

**Comment by taisazero** [comment]
Perfect! We can work on it together perhaps. I haven't started to be honest. We can coordinate on Discord. Tag @Erfan in the CarperAI discord #code-pile. @PhungVanDuy

**Comment by PhungVanDuy** [comment]
Books dev branch: https://github.com/CarperAI/Code-Pile/tree/books_dataset

**Comment by PhungVanDuy** [comment]
@taisazero  New dev folk here: https://github.com/PhungVanDuy/Code-Pile/tree/books_dataset

Updated dataset keep code block [this](https://drive.google.com/drive/folders/1pbogfVNhh-ZOpOeM_urbnA4QThF9yBKs?usp=sharing)

Next steps I will work  on [free-programming-books](https://github.com/EbookFoundation/free-programming-books) is that okay?

**Comment by taisazero** [comment]
> @taisazero New dev folk here: https://github.com/PhungVanDuy/Code-Pile/tree/books_dataset
> 
> Updated dataset keep code block [this](https://drive.google.com/drive/folders/1pbogfVNhh-ZOpOeM_urbnA4QThF9yBKs?usp=sharing)
> 
> Next steps I will work on [free-programming-books](https://github.com/EbookFoundation/free-programming-books) is that okay?

Yes, that's perfect! Whenever you're ready make a PR for Wikibooks though! Do you want to work on PDFs or websites first?

**Comment by ncoop57** [comment]
Wow this is freaking fire!!!!! I'm so excited for this subset 🤓

**Comment by PhungVanDuy** [comment]
PR: https://github.com/CarperAI/Code-Pile/pull/22

@taisazero @ncoop57  please review and give me a comment, maybe I miss something about the code structure for our CodePile project. It's will help me improve my later PR.

**Comment by PhungVanDuy** [comment]
> 

@taisazero  Do you have any priority list to work on? I have planned on this [free-programming-books](https://github.com/EbookFoundation/free-programming-books) for PDF first, but if you have any priority list it would be great.

**Comment by PhungVanDuy** [comment]
Besides the resource from github link above, I will try to get book from [BookSC](https://vi.b-ok.asia/s/programming?). If have any problem about license we just index not release.

**Comment by ncoop57** [comment]
@PhungVanDuy and @taisazero please the following information to the issue description:

## Tests

Include a dummy_dataset.parquet file to test your code against. This dummy_dataset should include the columns for the data and metadata associated with the dataset, which will then be converted into the final format for language model consumption, along with an example row or rows that you can verify your code correctly collects. In addition to this file, include the unit test that evaluates your code against this dummy_dataset.

Give an example of the columns and data:

| col1 | col2 | .... |
| ---- | ---- | ---- |
| row1 | row1 | .... |

**Comment by ncoop57** [comment]
gonna close this as it seems it is done in our spreadsheet.
