### ISSUE TITLE
UseNet

### ISSUE THREAD

**Issue by Jehoshaph** [CarperAI/Code-Pile#16]
## UseNet

Dataset URL - ~~[UsenetArchives](https://www.usenetarchives.com/?c=comp.&p=1) and~~ [InternetArchive](https://archive.org/details/usenet)

Does the dataset exists in a scraped format ?   No

## Procedure

- [x] Download appropriate dumps
- [x] Cleanup and de-duplicate ([Example](http://www.psych.ualberta.ca/~westburylab/downloads/usenetcorpus.download.html))
- [x] ~~Tag code blocks~~
- [x] Format in the standard [forum format](https://docs.google.com/document/d/18bIWrF6b8eltKTw0Spn8A3geyuwh69jzCK9yjmBIucc/edit)

**Comment by Jehoshaph** [comment]
Working on the cleanup and de-duplicate scripts

**Comment by ncoop57** [comment]
@Jehoshaph Might be better to just directly use the existing usenet dump that you linked or this uncleaned version they mention: https://aws.amazon.com/datasets/the-westburylab-usenet-corpus/. 

Is there any other dedup/cleanup steps you want to run?

**Comment by Jehoshaph** [comment]
A couple of potential issues with that dataset. They still haven't responded to my request for access to the dataset.

1. Their dataset only covers 2005 - 2010. The archives on Internet Archive go back to 1997.
2. "Documents that contained less than 90% English words were omitted. (English words were defined as words that are contained in a 100,000 words dictionary of english)." - I don't know if this excluded the coding archives, I'd need access to the dataset to check if archives like Java programming, etc. survived.
 

> Is there any other dedup/cleanup steps you want to run?

The only additional step is excluding messages with no replies.

**Comment by ncoop57** [comment]
@Jehoshaph 

ah okay, thanks for clearing that up. Yeah in that case, it makes sense to do it ourselves
