### ISSUE TITLE
Google Code Jam Project - Archive

### ISSUE THREAD

**Issue by reshinthadithyan** [CarperAI/Code-Pile#18]
## Google Code Jam Project - Archive

Dataset URL - [here](https://github.com/Jur1cek/gcj-dataset)

Does the dataset exist in a scraped format?   
Yes - [here](https://github.com/Jur1cek/gcj-dataset)

## Description
Google Code Jam is one of the most famous programming contests conducted with large scale participation 

## Procedure
- [x] Add Downloader
- [x] Decompress `.bz`
- [x] post-process

**Comment by PhungVanDuy** [comment]
Let me take this one also, this same type with Competitive Programming Dataset that I am working on. https://github.com/CarperAI/Code-Pile/issues/7

**Comment by reshinthadithyan** [comment]
@PhungVanDuy, are you taking this up ?

**Comment by PhungVanDuy** [comment]
@reshinthadithyan checked it but this data missed problem description, we need to write crawler to get it. I still not have time for this, I am working with books for a while, but I will back for this soon.

**Comment by PhungVanDuy** [comment]
@reshinthadithyan checked more detail today, so https://github.com/Jur1cek/gcj-dataset this dataset crawled from https://code.google.com/codejam/contest/ but currently this site have down, so Google code jam move to a new page https://codingcompetitions.withgoogle.com/codejam we need to write new crawler. I will write it, asap.

**Comment by PhungVanDuy** [comment]
Added Google Code Jam to Competitive Programming Dataset, check it at https://github.com/CarperAI/Code-Pile/pull/24/commits/b7562e99dbfeb180ff743cd593a211d2ea5bfc35 
cc @reshinthadithyan  @ncoop57

**Comment by ncoop57** [comment]
Resolved in #24
