### ISSUE TITLE
Google AI4Code – Kaggle

### ISSUE THREAD

**Issue by PhungVanDuy** [CarperAI/Code-Pile#28]
## Title
Google AI4Code – Understand Code in Python Notebooks

Dataset URL - [here](https://www.kaggle.com/competitions/AI4Code/data)

Does the dataset exists in a scraped format ?   
URL if Yes - [here](https://www.kaggle.com/competitions/AI4Code/data)

## Description
The dataset comprises about 160,000 Jupyter notebooks published by the Kaggle community. Jupyter notebooks are the tool of choice for many data scientists for their ability to tell a narrative with both code and natural language. These two types of discourse are contained within cells of the notebook, and we refer to these cells as either code cells or markdown cells ([markdown](https://en.wikipedia.org/wiki/Markdown) being the text formatting language used by Jupyter).

## Procedure

- [x]  Download Kaggle Dataset
- [x]  Process the dataset 

## Tests

Include a dummy_dataset.parquet file to test your code against. This dummy_dataset should include the columns for the data and metadata associated with the dataset, which will then be converted into the final format for language model consumption, along with an example row or rows that you can verify your code correctly collects. In addition to this file, include the unit test that evaluates your code against this dummy_dataset.

Give an example of the columns and data:

| col1 | col2 | .... |
| ---- | ---- | ---- |
| row1 | row1 | .... |

**Comment by PhungVanDuy** [comment]
PR: https://github.com/CarperAI/Code-Pile/pull/29 

cc @ncoop57  @reshinthadithyan

**Comment by ncoop57** [comment]
Resolved in #29
