### ISSUE TITLE
Leetcode

### ISSUE THREAD

**Issue by dmahan93** [CarperAI/Code-Pile#8]
## Leetcode

Dataset URL - [here](https://leetcode.com/problemset/all/)

Does the dataset exists in a scraped format ?   No
URL if Yes - [here]()

## Description
Leetcode contains many computer science programming questions with a rich community to share solutions and discuss the problem

## Procedure
- [ ] Scrape the website
- [ ] Formulate appropriate filters if at all we want to.
- [ ] Processing and formatting.
- [ ] lm_dataformat Processing

**Comment by Dahoas** [comment]
Does this fall under issue #7?

**Comment by dmahan93** [comment]
Closing since this is covered by #7

**Comment by faraday** [comment]
I'm working on this (as noted at #7 )
